- id: '1615338219902'
  alias: Living Room Light Switch (Lamps)
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.sonoff_mini_1_switch_1
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.toggle
    data:
      brightness: 255
    target:
      entity_id: light.living_room_lights
  mode: single
- id: '1616599090779'
  alias: Living Room Hall Switch
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_light_switch
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.dining_lights
    data:
      brightness: 204
  mode: single
- id: '1620780488824'
  alias: Dining Light Switch
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.sonoff_mini_1_switch
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.dining_lights
    data:
      brightness: 204
  mode: single
