- id: '1615338219902'
  alias: Living Room Light Switch
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.sonoff_mini_1_switch_1
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.toggle
    data:
      brightness: 255
    target:
      entity_id: light.living_room_lights
  mode: single
- id: '1616599090779'
  alias: Living Room Hall Switch
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.sonoff_mini_2_switch
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.toggle
    target:
      entity_id: switch.sonoff_mini_1_relay
  mode: single
