- platform: group
  name: Living Room Lights
  entities:
      - light.sb50_1
      - light.om100_1
      - light.om100_2
- platform: group
  name: T.J.'s Bedroom Lamp
  entities:
      - light.t_j_s_bedroom_lamp_1
      - light.t_j_s_bedroom_lamp_2
- platform: group
  name: Bedroom Lights
  entities:
      - light.t_j_s_bedroom_lamp_1
      - light.t_j_s_bedroom_lamp_2
      - light.nina_s_bedroom_lamp
      - light.sex_cave