esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  includes:
    - sb50_r.h
  on_boot:
    then:
      - light.turn_on:
          id: $devicename
          brightness: 80%
          white: 1.0
          color_temperature: 259 mireds 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: $lan_address
  reboot_timeout: 60min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${readable_devicename} Hotspot
    password: !secret ap_password

captive_portal:

logger:
  # Disable logging to serial
  baud_rate: 0

api:
  password: !secret api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_password

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_white
    pin: GPIO5

light:
  - platform: custom
    lambda: |-
      auto light_out = new SB50_r(id(output_red), id(output_green), id(output_blue), id(output_white));
      App.register_component(light_out);
      return {light_out};
    lights:
      - name: $devicename
        id: $devicename
        effects:
          - random:
          - strobe:
          - flicker:

sensor:
  - platform: wifi_signal
    name: ${readable_devicename} Wifi Signal
    update_interval: 60s