esphome:
  name: esp32c6-2
  on_boot:
        priority: -10
        then:
            # Enable external antenna by default (FM8625H RF switch)
            - output.turn_off: ant_gpio3     # LOW -> RF switch power ON
            - output.turn_on:  ant_gpio14    # HIGH -> external antenna (U.FL)

esp32:
  board: seeed_xiao_esp32c6
  variant: ESP32C6
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG
  baud_rate: 115200
  hardware_uart: USB_SERIAL_JTAG

# Enable Home Assistant API
api:
  encryption:
    key: "jJ6ftmKT1C9AMEnpfXToacZ3TBTPQVfYKNLSFe5106A="

ota:
  - platform: esphome
    password: !secret ota_password

network:
  enable_ipv6: true

openthread:
  tlv: !secret openthread_tlv
light:
  - platform: status_led
    name: "ESP32C6-2 LED"
    pin:
      number: GPIO15
      inverted: true

# Buttons
button:
    - platform: restart
      name: "Restart Device"

output:
      # External antenna control (GPIO3 power, GPIO14 select - FM8625H RF switch)
    - platform: gpio
      id: ant_gpio3
      pin: GPIO3

    - platform: gpio
      id: ant_gpio14
      pin: GPIO14

sensor:
    - platform: internal_temperature
      name: "Internal Temp"
      entity_category: diagnostic

    - platform: uptime
      name: "Uptime"
      unit_of_measurement: "h"
      accuracy_decimals: 2
      update_interval: 60s
      filters:
          - lambda: return x / 3600.0;
      entity_category: diagnostic

text_sensor:
  - platform: openthread_info
    ip_address:
      name: "Thread IP Address"
    channel:
      name: "Thread Channel"
    role:
      name: "Thread Device Role"
    rloc16:
      name: "Thread RLOC16"
    ext_addr:
      name: "Thread Extended Address"
    eui64:
      name: "Thread EUI64"
    network_name:
      name: "Thread Network Name"
    network_key:
      name: "Thread Network Key"
    pan_id:
      name: "Thread PAN ID"
    ext_pan_id:
      name: "Thread Extended PAN ID"
