substitutions:
  devicename: living_room_switch
  readable_devicename: Living Room Switch

esphome:
  name: $devicename
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: living-room-switch.lan

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${readable_devicename} Hotspot
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

api:
  password: !secret api_password

ota:
  password: !secret ota_password

status_led:
  pin: GPIO2

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: True
      mode: INPUT_PULLUP
    name: "Living Room Light Switch"
    filters:
      - delayed_on: 50ms
      - delayed_off: 20ms