esphome:
  name: living_room_sensor
  platform: ESP32
  board: nodemcu-32s
  includes:
    - om100.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.203
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: Living Room Sensor Hotspot
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

api:
  password: !secret api_password

ota:
  password: !secret ota_password

i2c:

sensor:
  - platform: bmp280
    temperature:
      name: "Living Room Temperature"
    pressure:
      name: "Living Room Pressure"
    address: 0x76
  - platform: dht
    pin: GPIO27
    temperature:
      name: "Living Room Temperature (AM2302)"
    humidity:
      name: "Living Room Humidity"
    model: AM2302
    update_interval: 60s
    
binary_sensor:
  - platform: status
    name: "Living Room Sensor Status"

# Define output pins
output:
  - platform: ledc
    id: output_red
    pin: GPIO4
  - platform: ledc
    id: output_green
    pin: GPIO12
  - platform: ledc
    id: output_blue
    pin: GPIO14
  - platform: ledc
    id: output_cold_white
    pin: GPIO5
  - platform: ledc
    id: output_warm_white
    pin: GPIO13
    
light:
  - platform: custom
    lambda: |-
      auto light_out = new OM100(id(output_red), id(output_green), id(output_blue), id(output_cold_white), id(output_warm_white));
      App.register_component(light_out);
      return {light_out};
    lights:
      - name: test_light_om100
        id: test_light_om100
