substitutions:
  devicename: master_bedroom_sensor
  readable_devicename: Master Bedroom Sensor
  lan_address: master-bedroom-sensor.lan

esphome:
  name: $devicename
  platform: ESP32
  board: esp32doit-devkit-v1

<<: include .bme280_sensor.yaml