substitutions:
  devicename: om100_1
  readable_devicename: OM100 1

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  includes:
    - om100.h
  on_boot:
    then:
      - lambda: |-
          auto call = id(${devicename}).turn_on();
          call.set_brightness(1.0);
          call.set_rgb(0.0, 0.0, 0.0);
          call.set_color_temperature(259); // 50% color temp
          call.perform();

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.214
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  reboot_timeout: 60min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${readable_devicename} Hotspot
    password: !secret ap_password

# Enable logging
logger:

api:
  password: !secret api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_password

# Define output pins
output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_white_brightness
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_white_color
    pin: GPIO13

light:
  - platform: custom
    lambda: |-
      auto light_out = new OM100(id(output_red), id(output_green), id(output_blue), id(output_white_color), id(output_white_brightness));
      App.register_component(light_out);
      return {light_out};
    lights:
      - name: $devicename
        id: $devicename


