substitutions:
  devicename: "sb50_2"
  readable_devicename: "SB50 2"

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  includes:
    - sb50.h
  on_boot:
    - then:
      - light.turn_on:
          id: $devicename
          brightness: 100%
          red: 100%
          green: 0%
          blue: 0%
          white: 0%

<<: !include .sb50.yaml