substitutions:
  devicename: sonoff_s31_1
  readable_devicename: Sonoff S31 1

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 60min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${readable_devicename} Hotspot
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

api:
  password: !secret api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${readable_devicename} Button
    on_click:
      max_length: 500ms
      then:
        - switch.toggle: s31_relay
  - platform: status
    name: ${readable_devicename} Status

status_led:
  pin:
    number: GPIO13
    inverted: True

switch:
  - platform: gpio
    id: s31_relay
    pin: GPIO12
    name: ${readable_devicename} Relay
